"""I12-S02 conformance tests for implementation story coverage reporting."""

from __future__ import annotations

import contextlib
import importlib.util
from io import StringIO
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TOOL = ROOT / "tools" / "story_coverage.py"


def load_story_coverage_module():
    spec = importlib.util.spec_from_file_location("story_coverage_tool", TOOL)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class StoryCoverageReportTests(unittest.TestCase):
    def test_backlog_story_parser_covers_i01_through_i23_rows(self) -> None:
        tool = load_story_coverage_module()

        stories = tool.implementation_story_ids(ROOT / "agile-impl-v0.1.md")

        self.assertIn("I01-S01", stories)
        self.assertIn("I12-S02", stories)
        self.assertIn("I15-S03", stories)
        self.assertIn("I16-S03", stories)
        self.assertIn("I17-S01", stories)
        self.assertIn("I18-S04", stories)
        self.assertIn("I19-S04", stories)
        self.assertIn("I20-S08", stories)
        self.assertIn("I21-S06", stories)
        self.assertIn("I22-S08", stories)
        self.assertIn("I23-S06", stories)
        self.assertEqual(len(stories), len(set(stories)))

    def test_report_classifies_tested_doc_only_and_missing_stories(self) -> None:
        tool = load_story_coverage_module()

        report = tool.coverage_report(ROOT)
        rows = {row.story: row for row in report.rows}

        self.assertEqual(rows["I01-S01"].status, "tested")
        self.assertEqual(rows["I01-S02"].status, "docs/tool")
        self.assertEqual(rows["I12-S02"].status, "tested")
        self.assertEqual(rows["I12-S03"].status, "tested")
        self.assertEqual(rows["I13-S02"].status, "tested")
        self.assertEqual(rows["I13-S03"].status, "tested")
        self.assertEqual(rows["I14-S01"].status, "tested")
        self.assertEqual(rows["I14-S02"].status, "tested")
        self.assertEqual(rows["I14-S03"].status, "tested")
        self.assertEqual(rows["I15-S01"].status, "tested")
        self.assertEqual(rows["I15-S02"].status, "tested")
        self.assertEqual(rows["I15-S03"].status, "tested")
        self.assertEqual(rows["I16-S01"].status, "tested")
        self.assertEqual(rows["I16-S02"].status, "tested")
        self.assertEqual(rows["I16-S03"].status, "tested")
        self.assertEqual(rows["I17-S01"].status, "tested")
        self.assertEqual(rows["I17-S02"].status, "tested")
        self.assertEqual(rows["I17-S03"].status, "tested")
        self.assertEqual(rows["I17-S04"].status, "tested")
        self.assertEqual(rows["I18-S01"].status, "tested")
        self.assertEqual(rows["I18-S02"].status, "tested")
        self.assertEqual(rows["I18-S03"].status, "tested")
        self.assertEqual(rows["I18-S04"].status, "tested")
        self.assertEqual(rows["I19-S02"].status, "tested")
        self.assertEqual(rows["I19-S03"].status, "tested")
        self.assertEqual(rows["I19-S04"].status, "tested")
        self.assertEqual(rows["I19-S01"].status, "docs/tool")
        self.assertEqual(rows["I20-S01"].status, "tested")
        self.assertEqual(rows["I20-S02"].status, "tested")
        self.assertEqual(rows["I20-S03"].status, "tested")
        self.assertEqual(rows["I20-S04"].status, "tested")
        self.assertEqual(rows["I20-S05"].status, "tested")
        self.assertEqual(rows["I20-S06"].status, "tested")
        self.assertEqual(rows["I20-S07"].status, "tested")
        self.assertEqual(rows["I20-S08"].status, "tested")
        self.assertEqual(rows["I21-S01"].status, "tested")
        self.assertEqual(rows["I21-S02"].status, "tested")
        self.assertEqual(rows["I21-S03"].status, "tested")
        self.assertEqual(rows["I21-S04"].status, "tested")
        self.assertEqual(rows["I21-S05"].status, "tested")
        self.assertEqual(rows["I21-S06"].status, "tested")
        self.assertEqual(rows["I22-S01"].status, "tested")
        self.assertEqual(rows["I22-S02"].status, "tested")
        self.assertEqual(rows["I22-S03"].status, "tested")
        self.assertEqual(rows["I22-S04"].status, "tested")
        self.assertEqual(rows["I22-S05"].status, "tested")
        self.assertEqual(rows["I22-S06"].status, "tested")
        self.assertEqual(rows["I22-S07"].status, "tested")
        self.assertEqual(rows["I22-S08"].status, "tested")
        self.assertEqual(rows["I23-S01"].status, "tested")
        self.assertEqual(rows["I23-S02"].status, "tested")
        self.assertEqual(rows["I23-S03"].status, "tested")
        self.assertEqual(rows["I23-S04"].status, "tested")
        self.assertEqual(rows["I23-S05"].status, "tested")
        self.assertEqual(rows["I23-S06"].status, "tested")
        self.assertEqual(rows["I30-S01"].status, "tested")
        self.assertEqual(rows["I30-S02"].status, "tested")
        self.assertEqual(rows["I30-S03"].status, "tested")
        self.assertEqual(rows["I30-S04"].status, "tested")
        self.assertEqual(rows["I30-S05"].status, "tested")
        self.assertEqual(rows["I30-S06"].status, "tested")
        self.assertEqual(rows["I31-S01"].status, "tested")
        self.assertEqual(rows["I31-S02"].status, "tested")
        self.assertEqual(rows["I31-S03"].status, "tested")
        self.assertEqual(rows["I31-S04"].status, "tested")
        self.assertEqual(rows["I31-S05"].status, "tested")
        self.assertEqual(rows["I31-S06"].status, "tested")
        self.assertEqual(rows["I32-S01"].status, "tested")
        self.assertEqual(rows["I32-S02"].status, "tested")
        self.assertEqual(rows["I32-S03"].status, "tested")
        self.assertEqual(rows["I32-S04"].status, "tested")
        self.assertGreater(report.tested_count, 0)
        self.assertEqual(report.missing_count, 8)

    def test_rendered_report_lists_artifacts_and_next_rtl_story(self) -> None:
        tool = load_story_coverage_module()

        rendered = tool.render_report(tool.coverage_report(ROOT))

        self.assertIn("# Implementation Story Coverage", rendered)
        self.assertIn("`I12-S02` | tested", rendered)
        self.assertIn("test_i12_s02_story_coverage.py", rendered)
        self.assertIn("`I15-S01` | tested", rendered)
        self.assertIn("`I15-S02` | tested", rendered)
        self.assertIn("`I15-S03` | tested", rendered)
        self.assertIn("`I16-S01` | tested", rendered)
        self.assertIn("`I16-S02` | tested", rendered)
        self.assertIn("`I16-S03` | tested", rendered)
        self.assertIn("`I17-S01` | tested", rendered)
        self.assertIn("relocatable-object-metadata.md", rendered)
        self.assertIn("`I17-S02` | tested", rendered)
        self.assertIn("linker-relocation-fixtures.md", rendered)
        self.assertIn("`I17-S03` | tested", rendered)
        self.assertIn("debug-metadata.md", rendered)
        self.assertIn("`I17-S04` | tested", rendered)
        self.assertIn("toolchain-regression-corpus.md", rendered)
        self.assertIn("`I18-S01` | tested", rendered)
        self.assertIn("user-process-entry.md", rendered)
        self.assertIn("`I18-S02` | tested", rendered)
        self.assertIn("vm-page-mapping.md", rendered)
        self.assertIn("`I18-S03` | tested", rendered)
        self.assertIn("user-syscall-demo.md", rendered)
        self.assertIn("`I18-S04` | tested", rendered)
        self.assertIn("minimal-scheduler.md", rendered)
        self.assertIn("`I19-S02` | tested", rendered)
        self.assertIn("endpoint-event-routing.md", rendered)
        self.assertIn("`I19-S03` | tested", rendered)
        self.assertIn("external-agent-transfers.md", rendered)
        self.assertIn("`I19-S04` | tested", rendered)
        self.assertIn("point-to-point-fabric-litmus.md", rendered)
        self.assertIn("`I19-S01` | docs/tool", rendered)
        self.assertIn("external-fabric-cpu-boundary.md", rendered)
        self.assertIn("`I20-S01` | tested", rendered)
        self.assertIn("rtl-first-slice-contract.md", rendered)
        self.assertIn("`I20-S02` | tested", rendered)
        self.assertIn("golden-retire-trace-corpus.md", rendered)
        self.assertIn("`I20-S03` | tested", rendered)
        self.assertIn("systemverilog-interface-spec.md", rendered)
        self.assertIn("`I20-S04` | tested", rendered)
        self.assertIn("verilator-differential-harness.md", rendered)
        self.assertIn("`I20-S05` | tested", rendered)
        self.assertIn("rtl-smoke-slice.md", rendered)
        self.assertIn("`I20-S06` | tested", rendered)
        self.assertIn("rtl-capability-memory-slice.md", rendered)
        self.assertIn("`I20-S07` | tested", rendered)
        self.assertIn("rtl-fault-trap-slice.md", rendered)
        self.assertIn("`I20-S08` | tested", rendered)
        self.assertIn("rtl-readiness-gap-report.md", rendered)
        self.assertIn("`I21-S01` | tested", rendered)
        self.assertIn("rtl-scalar-control-slice.md", rendered)
        self.assertIn("`I21-S02` | tested", rendered)
        self.assertIn("rtl-mmu-tlb-slice.md", rendered)
        self.assertIn("`I21-S03` | tested", rendered)
        self.assertIn("rtl-atomic-cache-slice.md", rendered)
        self.assertIn("`I21-S04` | tested", rendered)
        self.assertIn("rtl-control-trap-slice.md", rendered)
        self.assertIn("`I21-S05` | tested", rendered)
        self.assertIn("verilator-regression-gate.md", rendered)
        self.assertIn("`I21-S06` | tested", rendered)
        self.assertIn("rtl-semantic-closure.md", rendered)
        self.assertIn("`I22-S01` | tested", rendered)
        self.assertIn("test_i22_s01_rtl_core_shell.py", rendered)
        self.assertIn("rtl-integrated-core-shell.md", rendered)
        self.assertIn("`I22-S02` | tested", rendered)
        self.assertIn("test_i22_s02_rtl_core_fetch_decode.py", rendered)
        self.assertIn("rtl-integrated-core-fetch-decode.md", rendered)
        self.assertIn("`I22-S03` | tested", rendered)
        self.assertIn("test_i22_s03_rtl_core_scalar_control.py", rendered)
        self.assertIn("rtl-integrated-core-scalar-control.md", rendered)
        self.assertIn("`I22-S04` | tested", rendered)
        self.assertIn("test_i22_s04_rtl_core_cap_mem.py", rendered)
        self.assertIn("rtl-integrated-core-cap-mem.md", rendered)
        self.assertIn("`I22-S05` | tested", rendered)
        self.assertIn("test_i22_s05_rtl_core_control_trap.py", rendered)
        self.assertIn("rtl-integrated-core-control-trap.md", rendered)
        self.assertIn("`I22-S06` | tested", rendered)
        self.assertIn("test_i22_s06_rtl_core_mmu_tlb.py", rendered)
        self.assertIn("rtl-integrated-core-mmu-tlb.md", rendered)
        self.assertIn("`I22-S07` | tested", rendered)
        self.assertIn("test_i22_s07_rtl_core_atomic_cache.py", rendered)
        self.assertIn("rtl-integrated-core-atomic-cache.md", rendered)
        self.assertIn("`I22-S08` | tested", rendered)
        self.assertIn("test_i22_s08_rtl_core_regression_gate.py", rendered)
        self.assertIn("rtl-integrated-core-regression-gate.md", rendered)
        self.assertIn("`I23-S01` | tested", rendered)
        self.assertIn("test_i23_s01_fpga_first_test_profile.py", rendered)
        self.assertIn("fpga_first_test.py", rendered)
        self.assertIn("fpga_first_test_profile.py", rendered)
        self.assertIn("`I23-S02` | tested", rendered)
        self.assertIn("test_i23_s02_fpga_top_wrapper.py", rendered)
        self.assertIn("fpga-top-wrapper.md", rendered)
        self.assertIn("cpu_v01_fpga_top.sv", rendered)
        self.assertIn("fpga_top.py", rendered)
        self.assertIn("fpga_top_wrapper.py", rendered)
        self.assertIn("`I23-S03` | tested", rendered)
        self.assertIn("test_i23_s03_fpga_memory_adapters.py", rendered)
        self.assertIn("fpga-memory-adapters.md", rendered)
        self.assertIn("cpu_v01_fpga_memories.sv", rendered)
        self.assertIn("fpga_memory.py", rendered)
        self.assertIn("fpga_memory_adapters.py", rendered)
        self.assertIn("`I23-S04` | tested", rendered)
        self.assertIn("test_i23_s04_fpga_smoke_firmware.py", rendered)
        self.assertIn("fpga-smoke-firmware.md", rendered)
        self.assertIn("cpu_v01_fpga_first_test_tb.sv", rendered)
        self.assertIn("fpga_smoke.py", rendered)
        self.assertIn("fpga_smoke_firmware.py", rendered)
        self.assertIn("`I23-S06` | tested", rendered)
        self.assertIn("fpga-first-test-plan.md", rendered)
        self.assertIn("`I30-S01` | tested", rendered)
        self.assertIn("fpga-soc-top-closure.md", rendered)
        self.assertIn("`I30-S02` | tested", rendered)
        self.assertIn("fpga-soc-top-decoder.md", rendered)
        self.assertIn("test_i30_s02_fpga_soc_top_decoder.py", rendered)
        self.assertIn("`I30-S03` | tested", rendered)
        self.assertIn("fpga-soc-top-peripherals.md", rendered)
        self.assertIn("test_i30_s03_fpga_soc_top_peripherals.py", rendered)
        self.assertIn("`I30-S04` | tested", rendered)
        self.assertIn("fpga-soc-loader-handoff.md", rendered)
        self.assertIn("test_i30_s04_fpga_soc_loader_handoff.py", rendered)
        self.assertIn("`I30-S05` | tested", rendered)
        self.assertIn("fpga-soc-top-smoke.md", rendered)
        self.assertIn("test_i30_s05_fpga_soc_top_smoke.py", rendered)
        self.assertIn("`I30-S06` | tested", rendered)
        self.assertIn("fpga-soc-top-archive.md", rendered)
        self.assertIn("test_i30_s06_fpga_soc_top_archive.py", rendered)
        self.assertIn("`I31-S01` | tested", rendered)
        self.assertIn("fpga-first-pass-build-bundle.md", rendered)
        self.assertIn("test_i31_s01_fpga_first_pass_bundle.py", rendered)
        self.assertIn("`I31-S02` | tested", rendered)
        self.assertIn("fpga-first-pass-gowin-build.md", rendered)
        self.assertIn("test_i31_s02_fpga_first_pass_gowin.py", rendered)
        self.assertIn("`I31-S03` | tested", rendered)
        self.assertIn("fpga-first-pass-programming.md", rendered)
        self.assertIn("test_i31_s03_fpga_first_pass_programming.py", rendered)
        self.assertIn("`I31-S04` | tested", rendered)
        self.assertIn("fpga-first-pass-replay.md", rendered)
        self.assertIn("test_i31_s04_fpga_first_pass_replay.py", rendered)
        self.assertIn("`I31-S05` | tested", rendered)
        self.assertIn("fpga-first-pass-archive.md", rendered)
        self.assertIn("test_i31_s05_fpga_first_pass_archive.py", rendered)
        self.assertIn("`I31-S06` | tested", rendered)
        self.assertIn("fpga-first-pass-retest-matrix.md", rendered)
        self.assertIn("test_i31_s06_fpga_first_pass_retest_matrix.py", rendered)
        self.assertIn("`I32-S01` | tested", rendered)
        self.assertIn("fpga-monitor-command-profile.md", rendered)
        self.assertIn("test_i32_s01_fpga_monitor_profile.py", rendered)
        self.assertIn("`I32-S02` | tested", rendered)
        self.assertIn("fpga-monitor-firmware-fixtures.md", rendered)
        self.assertIn("test_i32_s02_fpga_monitor_firmware.py", rendered)
        self.assertIn("`I32-S03` | tested", rendered)
        self.assertIn("fpga-monitor-multi-program-session.md", rendered)
        self.assertIn("test_i32_s03_fpga_monitor_session.py", rendered)
        self.assertIn("`I32-S04` | tested", rendered)
        self.assertIn("fpga-monitor-debug-snapshot.md", rendered)
        self.assertIn("test_i32_s04_fpga_monitor_snapshot.py", rendered)

    def test_missing_only_cli_filters_report_rows(self) -> None:
        tool = load_story_coverage_module()
        stream = StringIO()

        with contextlib.redirect_stdout(stream):
            result = tool.main(["--missing-only"])

        output = stream.getvalue()
        self.assertEqual(result, 0)
        self.assertIn("Stories: 8", output)
        self.assertIn("Missing: 8", output)
        self.assertIn("`I33-S06` | missing", output)
        self.assertNotIn("`I32-S04` | missing", output)
        self.assertNotIn("`I32-S03` | missing", output)
        self.assertNotIn("`I32-S02` | missing", output)
        self.assertNotIn("`I32-S01` | missing", output)
        self.assertNotIn("`I31-S06` | missing", output)
        self.assertNotIn("`I31-S05` | missing", output)
        self.assertNotIn("`I31-S04` | missing", output)
        self.assertNotIn("`I31-S03` | missing", output)
        self.assertNotIn("`I31-S02` | missing", output)
        self.assertNotIn("`I31-S01` | missing", output)
        self.assertNotIn("`I30-S06` | missing", output)
        self.assertNotIn("`I30-S04` | missing", output)
        self.assertNotIn("`I21-S01` | tested", output)
        self.assertNotIn("`I21-S02` | tested", output)
        self.assertNotIn("`I21-S03` | tested", output)
        self.assertNotIn("`I21-S04` | tested", output)
        self.assertNotIn("`I21-S05` | tested", output)
        self.assertNotIn("`I21-S06` | tested", output)
        self.assertNotIn("`I22-S01` | tested", output)
        self.assertNotIn("`I22-S02` | tested", output)
        self.assertNotIn("`I22-S03` | tested", output)
        self.assertNotIn("`I22-S04` | tested", output)
        self.assertNotIn("`I22-S05` | tested", output)
        self.assertNotIn("`I22-S06` | tested", output)
        self.assertNotIn("`I22-S07` | tested", output)
        self.assertNotIn("`I22-S08` | tested", output)
        self.assertNotIn("`I23-S01` | tested", output)
        self.assertNotIn("`I23-S02` | tested", output)
        self.assertNotIn("`I23-S03` | tested", output)
        self.assertNotIn("`I23-S04` | tested", output)
        for story in ("I23-S05", "I23-S06", "I30-S01", "I30-S02", "I30-S03"):
            self.assertNotIn(f"`{story}` | tested", output)
        self.assertNotIn("`I18-S01` | tested", output)
        self.assertNotIn("`I18-S02` | tested", output)
        self.assertNotIn("`I18-S03` | tested", output)
        self.assertNotIn("`I18-S04` | tested", output)
        self.assertNotIn("`I19-S02` | tested", output)
        self.assertNotIn("`I19-S03` | tested", output)
        self.assertNotIn("`I19-S04` | tested", output)
        self.assertNotIn("`I17-S01` | tested", output)
        self.assertNotIn("`I17-S02` | tested", output)
        self.assertNotIn("`I17-S03` | tested", output)
        self.assertNotIn("`I17-S04` | tested", output)
        self.assertNotIn("`I19-S01` | docs/tool", output)
        self.assertNotIn("`I20-S01` | tested", output)
        self.assertNotIn("`I20-S02` | tested", output)
        self.assertNotIn("`I20-S03` | tested", output)
        self.assertNotIn("`I20-S04` | tested", output)
        self.assertNotIn("`I20-S05` | tested", output)
        self.assertNotIn("`I20-S06` | tested", output)
        self.assertNotIn("`I20-S07` | tested", output)
        self.assertNotIn("`I20-S08` | tested", output)
        self.assertNotIn("`I15-S03` | tested", output)
        self.assertNotIn("`I01-S01` | tested", output)

    def test_documentation_artifact_names_command_and_statuses(self) -> None:
        text = (ROOT / "docs" / "implementation" / "story-coverage.md").read_text(
            encoding="utf-8"
        )

        self.assertIn("Story: I12-S02", text)
        self.assertIn("python tools\\story_coverage.py", text)
        self.assertIn("`tested`", text)
        self.assertIn("`docs/tool`", text)
        self.assertIn("`missing`", text)


if __name__ == "__main__":
    unittest.main()
