package cpu_v01_pkg;
  localparam int CELL_BITS = 24;
  localparam int ADDR_BITS = 48;
  localparam int FETCH_GROUP_CELLS = 2;
  localparam int INTEGER_OBJECT_CELLS = 2;
  localparam int CAPABILITY_OBJECT_CELLS = 4;
  localparam int CAP_PAYLOAD_BITS = 96;
  localparam int CAP_CURSOR_BITS = 48;
  localparam int CAP_BOUNDS_METADATA_BITS = 30;
  localparam int CAP_PERMISSION_BITS = 8;
  localparam int CAP_OTYPE_BITS = 8;
  localparam int CAP_FLAG_BITS = 2;
  localparam int CAP_TAG_BITS = 1;
  localparam int INT_REG_BITS = 48;
  localparam int INT_REG_COUNT = 16;
  localparam int CAP_REG_COUNT = 8;
  localparam int CSR_BITS = 48;
  localparam int CSR_NUMBER_BITS = 8;
  localparam int CCSR_NUMBER_BITS = 8;
  localparam int OPCODE_ID_BITS = 8;
  localparam int RETIRE_SEQUENCE_BITS = 64;
  localparam int TLB_INVALIDATE_KIND_BITS = 3;
  localparam int MEMORY_TYPE_BITS = 2;
  localparam int CACHE_MAINT_KIND_BITS = 2;

  localparam logic [OPCODE_ID_BITS-1:0] OPC_CPY_24 = 8'h10;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_NEG_24 = 8'h11;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_ADD_24 = 8'h12;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_ADDU_24 = 8'h13;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SUB_24 = 8'h14;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SUBU_24 = 8'h15;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_MUL_24 = 8'h16;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_MULU_24 = 8'h17;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_DIV_24 = 8'h18;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_DIVU_24 = 8'h19;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_MOD_24 = 8'h1A;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_MODU_24 = 8'h1B;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_NOT_24 = 8'h1C;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_AND_24 = 8'h1D;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_OR_24 = 8'h1E;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_XOR_24 = 8'h1F;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SHL_24 = 8'h20;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SHRS_24 = 8'h21;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SHRU_24 = 8'h22;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_ROL_24 = 8'h23;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_ROR_24 = 8'h24;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CMP_24 = 8'h25;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CMPU_24 = 8'h26;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_TST_24 = 8'h27;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SETCC_24 = 8'h28;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CMOVCC_24 = 8'h29;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_BSET_24 = 8'h2A;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_BCLR_24 = 8'h2B;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_LD48_24 = 8'h30;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_ST48_24 = 8'h31;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CLC_24 = 8'h32;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSC_24 = 8'h33;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_LL48_24 = 8'h34;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SC48_24 = 8'h35;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CMOVE_48 = 8'h40;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CGETADDR_48 = 8'h41;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSETADDR_48 = 8'h42;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CANDPERM_48 = 8'h45;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_BRA_24 = 8'h50;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_BCC_24 = 8'h51;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CALL_24 = 8'h52;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_RET_12 = 8'h53;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_JMP_24 = 8'h54;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_BRK_12 = 8'h55;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SYS_12 = 8'h56;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SCALL_12 = OPC_SYS_12;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_IRET_24 = 8'h57;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_EPCCRD_24 = 8'h58;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_EPCCWR_24 = 8'h59;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_WFI_12 = 8'h5A;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_PAUSE_12 = 8'h5B;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CALLC_24 = 8'h5C;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_FENCE_24 = 8'h60;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_FENCE_I_24 = 8'h61;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SFENCE_VM_24 = 8'h62;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SFENCE_VM_ASID_24 = 8'h63;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SFENCE_VM_VA_24 = 8'h64;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_SFENCE_VM_VA_ASID_24 = 8'h65;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSRRD_24 = 8'h66;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSRWR_24 = 8'h67;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSRSET_24 = 8'h68;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSRCLR_24 = 8'h69;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSRRD_48 = 8'h6A;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSRWR_48 = 8'h6B;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSRSET_48 = 8'h6C;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CSRCLR_48 = 8'h6D;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CCSRRD_48 = 8'h70;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CCSRWR_48 = 8'h71;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CACHE_CLEAN_24 = 8'h80;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CACHE_INVAL_24 = 8'h81;
  localparam logic [OPCODE_ID_BITS-1:0] OPC_CACHE_CLEANINVAL_24 = 8'h82;
  localparam logic [15:0] EXC_ILLEGAL_INSTRUCTION = 16'h0001;
  localparam logic [15:0] EXC_BREAKPOINT = 16'h0002;
  localparam logic [15:0] EXC_PRIVILEGE_FAULT = 16'h0003;
  localparam logic [15:0] EXC_DIVIDE_BY_ZERO = 16'h0004;
  localparam logic [15:0] EXC_ALIGN_FAULT = 16'h0005;
  localparam logic [15:0] EXC_ACCESS_FAULT = 16'h0006;
  localparam logic [15:0] EXC_PAGE_FAULT = 16'h0007;
  localparam logic [15:0] EXC_SYSCALL_TRAP = 16'h0008;
  localparam logic [15:0] EXC_CAPABILITY_TAG_FAULT = 16'h0009;
  localparam logic [15:0] EXC_CAPABILITY_BOUNDS_FAULT = 16'h000A;
  localparam logic [15:0] EXC_CAPABILITY_PERMISSION_FAULT = 16'h000B;
  localparam logic [15:0] EXC_CAPABILITY_SEAL_TYPE_FAULT = 16'h000C;
  localparam logic [15:0] EXC_CAPABILITY_LOCAL_STORE_FAULT = 16'h000D;
  localparam logic [15:0] EXC_RETURN_STACK_UNDERFLOW = 16'h0030;
  localparam logic [15:0] EXC_RETURN_STACK_OVERFLOW = 16'h0031;
  localparam logic [15:0] EXC_RETURN_STACK_PERMISSION_FAULT = 16'h0032;
  localparam logic [3:0] CAPCAUSE_NONE = 4'h0;
  localparam logic [3:0] CAPCAUSE_TAG = 4'h1;
  localparam logic [3:0] CAPCAUSE_BOUNDS = 4'h2;
  localparam logic [3:0] CAPCAUSE_PERMISSION = 4'h3;
  localparam logic [3:0] CAPCAUSE_SEAL_TYPE = 4'h4;
  localparam logic [3:0] CAPCAUSE_LOCAL_STORE = 4'h5;
  localparam logic [7:0] FAULT_CAP_IDX_NONE = 8'h00;
  localparam logic [7:0] FAULT_CAP_IDX_C0 = 8'h10;
  localparam logic [7:0] FAULT_CAP_IDX_C1 = 8'h11;
  localparam logic [7:0] FAULT_CAP_IDX_C2 = 8'h12;
  localparam logic [7:0] FAULT_CAP_IDX_PCC = 8'h20;
  localparam logic [7:0] FAULT_CAP_IDX_RSC = 8'h23;
  localparam logic [7:0] FAULT_CAP_IDX_EPCC = 8'h26;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_SR = 8'h00;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_COREID = 8'h01;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_CYCLE = 8'h02;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_INSTRET = 8'h03;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_TVEC = 8'h04;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_CAUSE = 8'h05;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_TVAL = 8'h06;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_SCRATCH = 8'h07;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_IENABLE = 8'h08;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_IPENDING = 8'h09;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_TIMER = 8'h0A;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_TIMECMP = 8'h0B;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_SATP = 8'h0C;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_ASID = 8'h0D;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_DEBUGCTL = 8'h0E;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_PERFSEL = 8'h0F;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_FAULTCAPIDX = 8'h4A;
  localparam logic [CSR_NUMBER_BITS-1:0] CSR_CAPCAUSE = 8'h4B;
  localparam logic [CCSR_NUMBER_BITS-1:0] CCSR_PCC = 8'h00;
  localparam logic [CCSR_NUMBER_BITS-1:0] CCSR_DSC = 8'h01;
  localparam logic [CCSR_NUMBER_BITS-1:0] CCSR_RSC = 8'h02;
  localparam logic [CCSR_NUMBER_BITS-1:0] CCSR_DDC = 8'h03;
  localparam logic [CCSR_NUMBER_BITS-1:0] CCSR_EPCC = 8'h04;
  localparam logic [CCSR_NUMBER_BITS-1:0] CCSR_TVC = 8'h05;
  localparam logic [CCSR_NUMBER_BITS-1:0] CCSR_KSC = 8'h06;
  localparam logic [CCSR_NUMBER_BITS-1:0] CCSR_KRC = 8'h07;
  localparam logic SLOT_0 = 1'b0;
  localparam logic SLOT_1 = 1'b1;
  localparam logic [2:0] SATP_MODE_BARE = 3'd0;
  localparam logic [2:0] SATP_MODE_RADIX4 = 3'd1;
  localparam int SATP_MODE_SHIFT = 45;
  localparam int SATP_ASID_SHIFT = 37;
  localparam int SATP_ROOT_PPN_SHIFT = 11;
  localparam logic [1:0] MEMORY_TYPE_NORMAL_COHERENT = 2'd0;
  localparam logic [1:0] MEMORY_TYPE_NORMAL_UNCACHEABLE = 2'd1;
  localparam logic [1:0] MEMORY_TYPE_DEVICE_ORDERED = 2'd2;
  localparam logic [1:0] MEMORY_TYPE_RESERVED = 2'd3;
  localparam int PTE_V_BIT = 0;
  localparam int PTE_U_BIT = 1;
  localparam int PTE_R_BIT = 2;
  localparam int PTE_W_BIT = 3;
  localparam int PTE_X_BIT = 4;
  localparam int PTE_G_BIT = 5;
  localparam int PTE_A_BIT = 6;
  localparam int PTE_SW_BIT = 7;
  localparam int PTE_MT_SHIFT = 8;
  localparam int PTE_RES0_BIT = 10;
  localparam int PTE_PPN_SHIFT = 11;
  localparam logic [TLB_INVALIDATE_KIND_BITS-1:0] TLB_INV_NONE = 3'd0;
  localparam logic [TLB_INVALIDATE_KIND_BITS-1:0] TLB_INV_ALL = 3'd1;
  localparam logic [TLB_INVALIDATE_KIND_BITS-1:0] TLB_INV_ASID = 3'd2;
  localparam logic [TLB_INVALIDATE_KIND_BITS-1:0] TLB_INV_VA = 3'd3;
  localparam logic [TLB_INVALIDATE_KIND_BITS-1:0] TLB_INV_VA_ASID = 3'd4;
  localparam logic [CACHE_MAINT_KIND_BITS-1:0] CACHE_MAINT_NONE = 2'd0;
  localparam logic [CACHE_MAINT_KIND_BITS-1:0] CACHE_MAINT_CLEAN = 2'd1;
  localparam logic [CACHE_MAINT_KIND_BITS-1:0] CACHE_MAINT_INVAL = 2'd2;
  localparam logic [CACHE_MAINT_KIND_BITS-1:0] CACHE_MAINT_CLEANINVAL = 2'd3;
  localparam logic [1:0] MEM_EFFECT_NONE = 2'd0;
  localparam logic [1:0] MEM_EFFECT_ST48 = 2'd1;
  localparam logic [1:0] MEM_EFFECT_CSC = 2'd2;
  localparam logic [1:0] MEM_EFFECT_RETURN_STACK_PUSH = 2'd3;

  typedef logic [CELL_BITS-1:0] cell_t;
  typedef logic [ADDR_BITS-1:0] addr_t;
  typedef logic [INT_REG_BITS-1:0] int_reg_t;

  typedef struct packed {
    logic [CAP_CURSOR_BITS-1:0] cursor;
    logic [CAP_BOUNDS_METADATA_BITS-1:0] bounds_metadata;
    logic [CAP_PERMISSION_BITS-1:0] permissions;
    logic [CAP_OTYPE_BITS-1:0] otype;
    logic [CAP_FLAG_BITS-1:0] flags;
  } cap_payload_t;

  typedef struct packed {
    cap_payload_t payload;
    logic tag;
  } cap_t;

  typedef struct packed {
    logic valid;
    logic [OPCODE_ID_BITS-1:0] opcode_id;
    logic [7:0] size_bits;
    logic privileged;
  } decoded_opcode_t;

  typedef struct packed {
    logic valid;
    logic [15:0] cause;
    addr_t pc_cell;
    logic slot;
    addr_t tval;
    logic [3:0] capcause;
    logic [7:0] fault_cap_idx;
  } fault_packet_t;

  typedef struct packed {
    logic valid;
    logic [RETIRE_SEQUENCE_BITS-1:0] sequence;
    addr_t pc_cell;
    logic slot;
    logic [1:0] instruction_length;
    decoded_opcode_t decoded;
    logic normal_valid;
    fault_packet_t fault;
    logic redirect_valid;
    cap_t redirect_target;
    logic redirect_slot;
    logic integer_write_valid;
    logic [3:0] integer_write_index;
    int_reg_t integer_write_value;
    logic capability_write_valid;
    logic [2:0] capability_write_index;
    cap_t capability_write_value;
    logic csr_write_valid;
    logic [CSR_NUMBER_BITS-1:0] csr_write_index;
    int_reg_t csr_write_value;
    logic ccsr_write_valid;
    logic [CCSR_NUMBER_BITS-1:0] ccsr_write_index;
    cap_t ccsr_write_value;
    logic [1:0] memory_effect_kind;
    addr_t memory_effect_address;
    int_reg_t memory_integer_value;
    cap_t memory_capability_value;
    logic tag_write_valid;
    logic tag_write_value;
    logic pcc_update_valid;
    cap_t pcc_update_value;
    logic pcc_update_slot;
    logic epcc_update_valid;
    cap_t epcc_update_value;
    logic epcc_update_slot;
    logic trap_entry_valid;
    cap_t trap_target;
    logic trap_target_slot;
    logic trap_frame_save_valid;
    logic trap_frame_restore_valid;
    cap_t trap_frame_epcc_value;
    logic trap_frame_epcc_slot;
    int_reg_t trap_frame_sr_value;
    logic syscall_service_valid;
    int_reg_t syscall_service_number;
    int_reg_t syscall_status;
    logic syscall_return_valid;
    int_reg_t syscall_return_d0;
    int_reg_t syscall_return_d1;
    cap_t syscall_return_c0;
    logic translation_valid;
    addr_t effective_address;
    addr_t physical_address;
    logic [MEMORY_TYPE_BITS-1:0] translation_memory_type;
    logic translation_tlb_hit;
    logic tlb_fill_valid;
    logic tlb_fill_global;
    logic [7:0] tlb_fill_asid;
    logic [2:0] page_walk_level;
    logic tlb_invalidate_valid;
    logic [TLB_INVALIDATE_KIND_BITS-1:0] tlb_invalidate_kind;
    addr_t tlb_invalidate_va;
    logic [7:0] tlb_invalidate_asid;
    logic reservation_install_valid;
    logic reservation_clear_valid;
    addr_t reservation_word_address;
    logic [MEMORY_TYPE_BITS-1:0] reservation_memory_type;
    logic sc_success;
    logic fence_order_valid;
    logic fence_i_valid;
    logic cache_maintenance_valid;
    logic [CACHE_MAINT_KIND_BITS-1:0] cache_maintenance_kind;
    addr_t cache_maintenance_address;
    addr_t cache_maintenance_length;
  } retire_packet_t;
endpackage
